apiVersion: v1
kind: Service
metadata:
  name: {{ template "mimir.fullname" . }}-gossip-ring
  labels:
    app: {{ template "mimir.name" . }}-gossip-ring
    chart: {{ template "mimir.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: gossip-ring
      port: {{ .Values.config.memberlist.bind_port }}
      protocol: TCP
      targetPort: {{ .Values.config.memberlist.bind_port }}
  publishNotReadyAddresses: true
  selector:
    gossip_ring_member: "true"
