apiVersion: v1
kind: Service
metadata:
  name: {{ template "mimir.fullname" . }}-store-gateway
  labels:
    app: {{ template "mimir.name" . }}-store-gateway
    chart: {{ template "mimir.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.store_gateway.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app: {{ template "mimir.name" . }}-store-gateway
    release: {{ .Release.Name }}
