{{- if and .Values.gateway.enabled .Values.gateway.basicAuth.enabled (not .Values.gateway.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimir.gatewayFullname" . }}
  labels:
    app: {{ include "mimir.name" . }}-gateway
    chart: {{ include "mimir.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  .htpasswd: |
    {{- tpl .Values.gateway.basicAuth.htpasswd $ | nindent 4 }}
{{- end }}
