version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.12.7
  linter:
    docker:
      - image: golangci/golangci-lint:v1.17

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: make

  test:
    executor: default
    steps:
      - checkout
      - run: make test

  lint:
    executor: linter
    steps:
      - checkout
      - run: make lint

workflows:
  build_accept_deploy:
    jobs:
      - lint
      - build
      - test
