apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.fullname" . }}-compactor
  labels:
    name: compactor
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      name: compactor
  serviceName: compactor
  template:
    metadata:
      labels:
        name: compactor
    spec:
      containers:
      - args:
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=example-bucket
        - -compactor.block-ranges=2h,12h,24h
        - -compactor.blocks-retention-period=0
        - -compactor.cleanup-interval=15m
        - -compactor.compaction-concurrency=1
        - -compactor.compaction-interval=30m
        - -compactor.compactor-tenant-shard-size=1
        - -compactor.data-dir=/data
        - -compactor.deletion-delay=2h
        - -compactor.max-closing-blocks-concurrency=2
        - -compactor.max-opening-blocks-concurrency=4
        - -compactor.ring.consul.hostname=consul.{{ .Release.Namespace }}.svc.cluster.local:8500
        - -compactor.ring.prefix=
        - -compactor.ring.store=consul
        - -compactor.ring.wait-stability-min-duration=1m
        - -compactor.split-and-merge-shards=0
        - -compactor.split-groups=1
        - -compactor.symbols-flushers-concurrency=4
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -target=compactor
        image: grafana/mimir:mimir-2.0.0
        imagePullPolicy: IfNotPresent
        name: compactor
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: 1
            memory: 6Gi
        volumeMounts:
        - mountPath: /data
          name: compactor-data
        - mountPath: /etc/mimir
          name: overrides
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 900
      volumes:
      - configMap:
          name: overrides
        name: overrides
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: compactor-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 250Gi
      storageClassName: standard