apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mimir.fullname" . }}-consul-sidekick
  labels:
  {{- include "mimir.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mimir.fullname" . }}-consul-sidekick
  labels:
  {{- include "mimir.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "mimir.fullname" . }}-consul-sidekick'
subjects:
- kind: ServiceAccount
  name: '{{ include "mimir.fullname" . }}-consul-sidekick'
  namespace: '{{ .Release.Namespace }}'