apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-ingester
  labels:
    name: ingester
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingester.type }}
  selector:
    name: ingester
  {{- include "mimir.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ingester.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.fullname" . }}-ingester
  labels:
    name: ingester
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      name: ingester
  serviceName: ingester
  template:
    metadata:
      labels:
        name: ingester
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: ingester
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -blocks-storage.backend=gcs
        - -blocks-storage.gcs.bucket-name=example-bucket
        - -blocks-storage.tsdb.block-ranges-period=2h
        - -blocks-storage.tsdb.close-idle-tsdb-timeout=13h
        - -blocks-storage.tsdb.dir=/data/tsdb
        - -blocks-storage.tsdb.isolation-enabled=false
        - -blocks-storage.tsdb.ship-interval=1m
        - -distributor.health-check-ingesters=true
        - -ingester.max-global-series-per-metric=20000
        - -ingester.max-global-series-per-user=150000
        - -ingester.ring.consul.hostname=consul.{{ .Release.Namespace }}.svc.cluster.local:8500
        - -ingester.ring.heartbeat-period=15s
        - -ingester.ring.heartbeat-timeout=10m
        - -ingester.ring.num-tokens=512
        - -ingester.ring.prefix=
        - -ingester.ring.replication-factor=3
        - -ingester.ring.store=consul
        - -ingester.ring.tokens-file-path=/data/tokens
        - -ingester.ring.unregister-on-shutdown=true
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc-max-concurrent-streams=10000
        - -server.grpc-max-recv-msg-size-bytes=10485760
        - -server.grpc-max-send-msg-size-bytes=10485760
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -target=ingester
        image: grafana/mimir:mimir-2.0.0
        imagePullPolicy: IfNotPresent
        name: ingester
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 25Gi
          requests:
            cpu: "4"
            memory: 15Gi
        volumeMounts:
        - mountPath: /data
          name: ingester-data
        - mountPath: /etc/mimir
          name: overrides
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 1200
      volumes:
      - configMap:
          name: overrides
        name: overrides
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ingester-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: fast