apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-memcached-frontend
  labels:
    name: memcached-frontend
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  type: {{ .Values.memcachedFrontend.type }}
  selector:
    name: memcached-frontend
  {{- include "mimir.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.memcachedFrontend.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.fullname" . }}-memcached-frontend
  labels:
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      name: memcached-frontend
  serviceName: memcached-frontend
  template:
    metadata:
      labels:
        name: memcached-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: memcached-frontend
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -m 1024
        - -I 5m
        - -c 1024
        - -v
        image: memcached:1.6.9-alpine
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: 500m
            memory: 1329Mi
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
  updateStrategy:
    type: RollingUpdate