apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-memcached-frontend
  labels:
    name: memcached-frontend
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  type: {{ .Values.memcachedFrontend.type }}
  selector:
    name: memcached-frontend
  {{- include "mimir.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.memcachedFrontend.ports | toYaml | nindent 2 -}}