apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-store-gateway
  labels:
    name: store-gateway
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storeGateway.type }}
  selector:
    name: store-gateway
  {{- include "mimir.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.storeGateway.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.fullname" . }}-store-gateway
  labels:
    name: store-gateway
  {{- include "mimir.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      name: store-gateway
  serviceName: store-gateway
  template:
    metadata:
      labels:
        name: store-gateway
    spec:
      containers:
      - args:
        - -blocks-storage.backend=gcs
        - -blocks-storage.bucket-store.chunks-cache.attributes-in-memory-max-items=50000
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=dnssrvnoa+memcached.{{
          .Release.Namespace }}.svc.cluster.local:11211
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-get-multi-concurrency=100
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-idle-connections=100
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-item-size=1048576
        - -blocks-storage.bucket-store.ignore-blocks-within=10h
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=dnssrvnoa+memcached-index-queries.{{
          .Release.Namespace }}.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.index-cache.memcached.max-get-multi-concurrency=100
        - -blocks-storage.bucket-store.index-cache.memcached.max-idle-connections=100
        - -blocks-storage.bucket-store.index-cache.memcached.max-item-size=5242880
        - -blocks-storage.bucket-store.index-header-lazy-loading-enabled=true
        - -blocks-storage.bucket-store.index-header-lazy-loading-idle-timeout=60m
        - -blocks-storage.bucket-store.max-chunk-pool-bytes=12884901888
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+memcached-metadata.{{
          .Release.Namespace }}.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-get-multi-concurrency=100
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-idle-connections=100
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-item-size=1048576
        - -blocks-storage.bucket-store.sync-dir=/data/tsdb
        - -blocks-storage.bucket-store.sync-interval=15m
        - -blocks-storage.gcs.bucket-name=example-bucket
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -store-gateway.sharding-ring.consul.hostname=consul.{{ .Release.Namespace
          }}.svc.cluster.local:8500
        - -store-gateway.sharding-ring.prefix=
        - -store-gateway.sharding-ring.replication-factor=3
        - -store-gateway.sharding-ring.store=consul
        - -store-gateway.sharding-ring.tokens-file-path=/data/tokens
        - -store-gateway.sharding-ring.wait-stability-min-duration=1m
        - -target=store-gateway
        image: grafana/mimir:mimir-2.0.0
        imagePullPolicy: IfNotPresent
        name: store-gateway
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 18Gi
          requests:
            cpu: "1"
            memory: 12Gi
        volumeMounts:
        - mountPath: /data
          name: store-gateway-data
        - mountPath: /etc/mimir
          name: overrides
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          name: overrides
        name: overrides
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: store-gateway-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: standard